
services:
  api:
    build: .
    image: alertapersona
    container_name: alertapersona-api
    restart: unless-stopped
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env


# services:
#   alerta-persona:
#     container_name: alerta-persona
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - '54001:54001'
#     env_file:
#       - .env
#     depends_on:
#       - mysql
#     networks:
#       - app-network
#     restart: always
#     command: sh -c "npx prisma migrate deploy && npm run start:dev"

#   mysql:
#     image: mysql:8.0
#     container_name: mysql-alerta
#     environment:
#       MYSQL_ROOT_PASSWORD: segura
#       MYSQL_DATABASE: alertapersona
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - app-network
#     restart: always

# networks:
#   app-network:
#     driver: bridge

# volumes:
#   mysql_data: