//@host = https://alerta-persona-api.julitorossian.dev
@host = http://localhost:4000

@baseUrl = {{host}}/api

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiSnVsaWFuIiwiZW1haWwiOiJqdWxpYW4udG9yb3NzaWFuQG91dGxvb2suY29tIiwiaWF0IjoxNzYyODE4OTU4LCJleHAiOjE3NjI4MjI1NTh9.nA0S_EM9Hu7briPAYti0KcgyTxjEmctPJuR6xOWtc4U
###

POST {{baseUrl}}/asistente/
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "alertaId": 1,
    "usuarioId": 7,
    "estado": "A"
}


###

GET {{baseUrl}}/asistente/
Authorization: Bearer {{token}}


###

GET {{baseUrl}}/asistente/alerta/68
Authorization: Bearer {{token}}

###

GET {{baseUrl}}/asistente/alerta/64/usuario/7
Authorization: Bearer {{token}}