

POST http://localhost:4000/api/alerta/
Content-Type: application/json

{
    "usuarioId": 7,
    "latitud": -39.9587501,
    "longitud": -71.084678
}


###

GET http://localhost:4000/api/alerta/


###

GET http://localhost:4000/api/alerta/6


###

PATCH http://localhost:4000/api/alerta/2/cerrar
Content-Type: application/json

{
    "id": 6,
    "estado": "S"
}


###

# Obtener alertas activas de mis contactos
GET http://localhost:4000/api/alerta/contactos/activas
Authorization: Bearer YOUR_TOKEN_HERE