# @host = http://localhost
# @port = 4000
@host = https://alerta-persona-api.julitorossian.dev

# @baseUrl = {{host}}:{{port}}/api/
@baseUrl = {{host}}/api

@token = {{login.response.body.access_token}}
###

# test iniciar sesion
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "mail": "julian.torossian@outlook.com",
    "password": "987654321"
}

###

GET {{baseUrl}}/auth/profile
Authorization: Bearer {{token}}


###

# Cambio de contraseña

POST {{baseUrl}}/auth/cambiar-contrasena
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nuevaContrasena": "987654321",
    "contrasenaActual": "123456789"
}
