@host = http://localhost:4000
# @host = https://alerta-persona-api.julitorossian.dev

# @baseUrl = {{host}}:{{port}}/api/
@baseUrl = {{host}}/api

@token = {{login.response.body.access_token}}
###

# test iniciar sesion
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "mail": "julian.torossian@outlook.com",
    "password": "987654321"
}

###

GET {{baseUrl}}/auth/profile
Authorization: Bearer {{token}}


###

# Cambio de contraseña

POST {{baseUrl}}/auth/cambiar-contrasena
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nuevaContrasena": "987654321",
    "contrasenaActual": "123456789"
}

###

POST {{baseUrl}}/auth/refresh
Content-Type: application/json

{
    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjEsInVzZXJuYW1lIjoiSnVsaWFuIiwiZW1haWwiOiJqdWxpYW4udG9yb3NzaWFuQG91dGxvb2suY29tIiwiaWF0IjoxNzY0NzE5Njg4LCJleHAiOjE3NjUzMjQ0ODh9.2H-5IDWiY4FmC9lpdPXlkL3y_la7XkUlzjNmMZWZ6hc"
}

