@host = http://localhost
@port = 4000
# @host = https://alerta-persona-api.julitorossian.dev

@baseUrl = {{host}}:{{port}}/api
# @baseUrl = {{host}}/api

@token = {{login.response.body.access_token}}
###

# get usuarios
GET {{baseUrl}}/usuario/
Authorization: Bearer {{token}}

###

# get usuario
GET {{baseUrl}}/usuario/7
Authorization: Bearer {{token}}

###

# Insert usuario
POST {{baseUrl}}/usuario/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "nombre": "julian",
    "apellido": "torossian",
    "nroDocumento": 99999997,
    "telefono": "2944909090",
    "genero": "m",
    "nroTramite": 20417510576,
    "mail": "mail2@mail.com",
    "password": "123456789"
}

###

# SET TOKEN

POST {{baseUrl}}/usuario/3/setNotificacionToken
Content-Type: application/json

{
    "id": "3",
    "token": "dvSXzuQjSoKSDfmlVBrHGLAPA91bG6OX7cIypZ3KMVwIBS8JoH9EnLfaSZgLCdoWB6ziL09Nmo5dlOu1PshRuDRy8X4xSN8pj1g8oQeIAU3phI8O9AJIW9DZriTi7RKlaCxG7UiG6B0dMGA01Ct14XCwUoDQ"
}

###

# test iniciar sesion
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "mail": "julian.torossian@outlook.com",
    "password": "123456789"
}

###

GET {{baseUrl}}/auth/profile
Authorization: Bearer {{token}}

###

# ver historial
GET {{baseUrl}}/usuario/4/historial
Authorization: Bearer {{token}}

###

# ver historial
GET {{baseUrl}}/usuario/historial-alertas/4
Authorization: Bearer {{token}}